name: Build Simulink Model for Arduino

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Check out repository code
    # Set up MATLAB
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        products: Simulink Simulink_Compiler Simulink_Test Simulink_Support_Package_for_Arduino_Hardware
    # Build the Simulink model for Arduino
    - name: Build Simulink Model
      uses: matlab-actions/run-build@v2
